version:                "3"
services:
  datascience-notebook:
      image:            jupyter/datascience-notebook
      volumes:
        - ./:/home/jovyan/work
      ports:
        - 8888:8888
      container_name:   icoOmen-model
